import bcrypt from 'bcryptjs';

const data = {
  config: {
    cambioManual: 2000,
    tasaIva: 12,
    otrosImp: 2,
    montoEnvio: 9,
    mostrarBs: false,
    mostrarBcv: false,
  },
  users: [
    {
      nombre: 'Franklin',
      apellido: 'Bolivar',
      cedula: 'V7884014',
      email: 'frank.uah@gmail.com',
      password: bcrypt.hashSync('1331', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        codigo: 'V0001',
        comision: 0.05,
        acumuladoVentas: 0,
        observaciones: 'Admin seller',
      },
    },
    {
      nombre: 'user1',
      apellido: 'user1',
      cedula: 'V000000000',
      email: 'user1@gmail.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
      isSeller: false,
    },
  ],

  productos: [
    {
      nombre: 'Camisa 1',
      imagen: '/images/p1.jpg',
      marca: 'Adidas',
      categoria: 'camisas',
      descripcion: 'Comoda camisa manga corta con bellos estampados',
      precio: 120,
      cloudImage: ' ',
      modelo: 'fitter',
      costo: 20,
      precioMayor: 27,
      precioDescuento: 28,
      precioEspecial: 25,
      precioDocena: 29,
      proveedor: '612b9334d5059ea31d3284bf',
      tags: [],
      inventario: 12,
    },
    {
      nombre: 'Torta Pascua',
      imagen: '/images/p2.jpg',
      marca: 'Divinas Tentaciones',
      categoria: 'tortas',
      descripcion: 'Deliciosa torta de chocolate y vainilla',
      precio: 60,
      cloudImage: ' ',
      modelo: 'fitter',
      costo: 20,
      precioMayor: 27,
      precioDescuento: 28,
      precioEspecial: 25,
      precioDocena: 29,
      proveedor: '612b9334d5059ea31d3284bf',
      tags: [],
      inventario: 12,
    },
    {
      nombre: 'Lito Coca-Cola',
      imagen: '/images/p3.jpg',
      marca: 'coca-cola',
      categoria: 'afiches',
      descripcion: 'Litografia Conmemorativa Aniversario de Coca-Cola',
      precio: 10.5,
      cloudImage: ' ',
      modelo: 'fitter',
      costo: 20,
      precioMayor: 27,
      precioDescuento: 28,
      precioEspecial: 25,
      precioDocena: 29,
      proveedor: '612b9334d5059ea31d3284bf',
      tags: [],
      inventario: 12,
    },
    {
      nombre: 'Torta Cumpleaños',
      imagen: '/images/p4.jpg',
      marca: 'divinas tentaciones',
      categoria: 'tortas',
      descripcion: 'Deliciosa torta de cumpleaños con figuras solicitadas',
      precio: 25,
      cloudImage: ' ',
      modelo: 'fitter',
      costo: 20,
      precioMayor: 27,
      precioDescuento: 28,
      precioEspecial: 25,
      precioDocena: 29,
      proveedor: '612b9334d5059ea31d3284bf',
      tags: [],
      inventario: 12,
    },
    {
      nombre: 'Dulce Variados',
      imagen: '/images/p5.jpg',
      marca: 'divinas tentaciones',
      categoria: 'dulces',
      descripcion: 'Deliciosos dulces variados',
      precio: 15.75,
      cloudImage: ' ',
      modelo: 'fitter',
      costo: 20,
      precioMayor: 27,
      precioDescuento: 28,
      precioEspecial: 25,
      precioDocena: 29,
      proveedor: '612b9334d5059ea31d3284bf',
      tags: [],
      inventario: 12,
    },
    {
      nombre: 'Reloj Fitbit',
      imagen: '/images/p6.jpg',
      marca: 'Takoi',
      categoria: 'relojes',
      descripcion: 'Practico reloj monitor de ejericios',
      precio: 32.75,
      cloudImage: ' ',
      modelo: 'fitter',
      costo: 20,
      precioMayor: 27,
      precioDescuento: 28,
      precioEspecial: 25,
      precioDocena: 29,
      proveedor: '612b9334d5059ea31d3284bf',
      tags: [],
      inventario: 12,
    },
    {
      nombre: 'Torta Carmin',
      imagen: '/images/p7.jpg',
      marca: 'divinas tentaciones',
      categoria: 'tortas',
      descripcion: 'Deliciosa torta de fresa y vainilla',
      precio: 32.75,
      cloudImage: ' ',
      modelo: 'fitter',
      costo: 20,
      precioMayor: 27,
      precioDescuento: 28,
      precioEspecial: 25,
      precioDocena: 29,
      proveedor: '612b9334d5059ea31d3284bf',
      tags: [],
      inventario: 12,
    },
    {
      nombre: 'Pantalon Crudo',
      imagen: '/images/p8.jpg',
      marca: 'dockers',
      categoria: 'pantalones',
      descripcion: 'Comodo pantalon color verde oliva',
      precio: 30.0,
      cloudImage: ' ',
      modelo: 'fitter',
      costo: 20,
      precioMayor: 27,
      precioDescuento: 28,
      precioEspecial: 25,
      precioDocena: 29,
      proveedor: '612b9334d5059ea31d3284bf',
      tags: [],
      inventario: 12,
    },
    {
      nombre: 'Pantalon Lino',
      imagen: '/images/p9.jpg',
      marca: 'dockers',
      categoria: 'pantalones',
      descripcion: 'Comodo pantalon color gris',
      precio: 35.0,
      cloudImage: ' ',
      modelo: 'fitter',
      costo: 20,
      precioMayor: 27,
      precioDescuento: 28,
      precioEspecial: 25,
      precioDocena: 29,
      proveedor: '612b9334d5059ea31d3284bf',
      tags: [],
      inventario: 12,
    },
    {
      nombre: 'Camisa Estampada',
      imagen: '/images/p10.jpg',
      marca: 'american-style',
      categoria: 'camisas',
      descripcion: 'Comoda camisa con ligeros estampados color blanca',
      precio: 23.0,
      cloudImage: ' ',
      modelo: 'fitter',
      costo: 20,
      precioMayor: 27,
      precioDescuento: 28,
      precioEspecial: 25,
      precioDocena: 29,
      proveedor: '612b9334d5059ea31d3284bf',
      tags: [],
      inventario: 12,
    },
    {
      nombre: 'Combo Hogar',
      imagen: '/images/p11.jpg',
      marca: 'amazon',
      categoria: 'tortas',
      descripcion: 'Dispositivo Alexa con accesorios',
      precio: 325.75,
      cloudImage: ' ',
      modelo: 'fitter',
      costo: 20,
      precioMayor: 27,
      precioDescuento: 28,
      precioEspecial: 25,
      precioDocena: 29,
      proveedor: '612b9334d5059ea31d3284bf',
      tags: [],
      inventario: 12,
    },
    {
      nombre: 'Pods IphoneX',
      imagen: '/images/p12.jpg',
      marca: 'toshiba',
      categoria: 'accesorios',
      descripcion: 'Duraderos ipods para iphone color azul celeste',
      precio: 15.0,
      cloudImage: ' ',
      modelo: 'fitter',
      costo: 20,
      precioMayor: 27,
      precioDescuento: 28,
      precioEspecial: 25,
      precioDocena: 29,
      proveedor: '612b9334d5059ea31d3284bf',
      tags: [],
      inventario: 12,
    },
  ],
};

export default data;
