const data = {
  products: [
    {
      _id: '1',
      sku: '',
      name: 'Sneakers Gucci',
      category: 'zapatos',
      image: '/images/p001.png',
      costo: 50,
      countInStock: 10,
      brand: 'Gucci',
      rating: 4.5,
      numReviews: 10,
      description:
        'Comodos sneakers para uso diario, con llamativo diseño estampado en diferentes colores.',
      price: 120,
      precios: [110, 100, 90],
      color: ['rojo', 'azul', 'verde'],
      modelo: 'lake',
      codigo: '',
      barcode: '',
      precioCompra: 50,
      precioMayor: 0,
      descuento: 0,
      proveedor: '',
      subcategoria: 'deportivo',
      genero: 'unisex',
      sizes: [36, 37, 38, 39, 40],
      tags: ['deportivos', 'comodo', 'trotar', 'sneakers', 'trenzas'],
      procedencia: 'importado',
      otros: [],
    },
    {
      _id: '2',
      sku: '',
      name: 'Gucci Modelo 001',
      category: 'zapatos',
      image: '/images/p003.png',
      costo: 50,
      countInStock: 10,
      brand: 'Gucci',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
      price: 120,
      precios: [],
      color: '',
      modelo: '',
      codigo: '',
      barcode: '',
      precioCompra: 0,
      precioMayor: 0,
      descuento: 0,
      proveedor: '',
      subcategoria: 'deportivo',
      genero: 'unisex',
      sizes: [],
      tags: ['deportivos', 'comodo', 'trotar', 'sneakers', 'trenzas'],
      procedencia: 'importado',
      otros: [],
    },
    {
      _id: '3',
      sku: '',
      name: 'Gucci Modelo 001',
      category: 'zapatos',
      image: '/images/p005.png',
      costo: 50,
      countInStock: 10,
      brand: 'Gucci',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
      price: 120,
      precios: [],
      color: '',
      modelo: '',
      codigo: '',
      barcode: '',
      precioCompra: 0,
      precioMayor: 0,
      descuento: 0,
      proveedor: '',
      subcategoria: 'deportivo',
      genero: 'unisex',
      sizes: [],
      tags: ['deportivos', 'comodo', 'trotar', 'sneakers', 'trenzas'],
      procedencia: 'importado',
      otros: [],
    },
    {
      _id: '4',
      sku: '',
      name: 'Gucci Modelo 001',
      category: 'zapatos',
      image: '/images/p007.png',
      costo: 50,
      countInStock: 10,
      brand: 'Gucci',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
      price: 120,
      precios: [],
      color: '',
      modelo: '',
      codigo: '',
      barcode: '',
      precioCompra: 0,
      precioMayor: 0,
      descuento: 0,
      proveedor: '',
      subcategoria: 'deportivo',
      genero: 'unisex',
      sizes: [],
      tags: ['deportivos', 'comodo', 'trotar', 'sneakers', 'trenzas'],
      procedencia: 'importado',
      otros: [],
    },
    {
      _id: '5',
      sku: '',
      name: 'Gucci Modelo 001',
      category: 'zapatos',
      image: '/images/p009.png',
      costo: 50,
      countInStock: 10,
      brand: 'Gucci',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
      price: 120,
      precios: [],
      color: '',
      modelo: '',
      codigo: '',
      barcode: '',
      precioCompra: 0,
      precioMayor: 0,
      descuento: 0,
      proveedor: '',
      subcategoria: 'deportivo',
      genero: 'unisex',
      sizes: [],
      tags: ['deportivos', 'comodo', 'trotar', 'sneakers', 'trenzas'],
      procedencia: 'importado',
      otros: [],
    },
    {
      _id: '6',
      sku: '',
      name: 'Gucci Modelo 001',
      category: 'zapatos',
      image: '/images/p011.png',
      costo: 50,
      countInStock: 10,
      brand: 'Gucci',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
      price: 120,
      precios: [],
      color: '',
      modelo: '',
      codigo: '',
      barcode: '',
      precioCompra: 0,
      precioMayor: 0,
      descuento: 0,
      proveedor: '',
      subcategoria: 'deportivo',
      genero: 'unisex',
      sizes: [],
      tags: ['deportivos', 'comodo', 'trotar', 'sneakers', 'trenzas'],
      procedencia: 'importado',
      otros: [],
    },
  ],
};
export default data;
